### ISSUE TITLE
What do i do?

### ISSUE THREAD

**Issue by EtchReborn** [pmt-mcpe-fun/Main#3]
![screenshot_2017-05-21-18-23-12](https://cloud.githubusercontent.com/assets/28599276/26285574/d9485ad2-3e52-11e7-9079-cdaa27c3215d.png)

**Comment by Ad5001** [comment]
Ok sorry for this. it should be fixed now.

**Comment by EtchReborn** [comment]
No problem can you invite me to this group or this project? I am good with websites style

**Comment by NFGamerMC** [comment]
Nope

**Comment by EtchReborn** [comment]
Why not? I wanna help

**Comment by Ad5001** [comment]
@EtchReborn What you can do is forking the project and add things with your own style and then make a PR.

**Comment by EtchReborn** [comment]
Oh great idea thanks :)
