### ISSUE TITLE
Phar to zip

### ISSUE THREAD

**Issue by EtchReborn** [pmt-mcpe-fun/Main#4]
When i tryed to use phar to zip on my other plugins it worked but when i did on my "Bounty plugin" and "MCMMO plugin" and "Crates.plugin" it shows these files and in those files is there only random codes
![screenshot_2017-05-21-21-19-49](https://cloud.githubusercontent.com/assets/28599276/26286692/f854ad68-3e6b-11e7-9f63-74856810e019.png)
![screenshot_2017-05-21-21-17-21](https://cloud.githubusercontent.com/assets/28599276/26286700/022131fe-3e6c-11e7-8fd3-f687469a6084.png)
![screenshot_2017-05-21-21-20-07](https://cloud.githubusercontent.com/assets/28599276/26286701/081f7b38-3e6c-11e7-8c18-767d1321d9b2.png)
![screenshot_2017-05-21-21-20-50](https://cloud.githubusercontent.com/assets/28599276/26286705/0ced6b0c-3e6c-11e7-9919-80e7756efc68.png)

**Comment by Ad5001** [comment]
So if it converted it properly to a zip, what's the problem?

**Comment by EtchReborn** [comment]
It converted it to zip but in some plugins the phar to zip dosent work cus i get the zip but in the zip there is random files with random codes that dosent anything releated to the plugin i want to be zip and It need to work on all plugins.. I think it is something with the website plugin.yml that is doing that maybe

**Comment by Ad5001** [comment]
Oh I know. Fixing that ASAP.

**Comment by Ad5001** [comment]
It should be fixed now :)

**Comment by EtchReborn** [comment]
![screenshot_2017-05-21-23-33-47](https://cloud.githubusercontent.com/assets/28599276/26287540/2432e046-3e7e-11e7-9782-f6db4758be06.png)
![screenshot_2017-05-21-23-33-47](https://cloud.githubusercontent.com/assets/28599276/26287542/29dea8f4-3e7e-11e7-91ff-61f814b3dbb3.png)

**Comment by EtchReborn** [comment]
![screenshot_2017-05-21-23-33-59](https://cloud.githubusercontent.com/assets/28599276/26287549/3c4b308e-3e7e-11e7-97a6-a31e1c11996e.png)

**Comment by EtchReborn** [comment]
How do i make it say pmt in preview too?

**Comment by EtchReborn** [comment]
![screenshot_2017-05-21-23-33-47](https://cloud.githubusercontent.com/assets/28599276/26287558/6a598f70-3e7e-11e7-96b1-9e000ad77eb8.png)
